spring:
 application:
    name: order
 datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
    url: jdbc:mysql://127.0.0.1/springcloud_sell?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
 jpa:
    show-sql: true
 mvc:
    async:
      request-timeout: 30000

eureka:
 client: 
   service-url:
    defaultZone: http://218.197.229.216:8761/eureka/
    #  http://localhost:8761/eureka/
    #http://218.197.229.216:8761/eureka/

server:
 port: 9102  
 



  